<a href="https://colab.research.google.com/github/shrinkhal14/Udacity-AI-program/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np
#stands for numerical python - a multidim array that is used to store same data types

In [22]:
x=np.random.random(1000000)

In [23]:
print(np.mean(x))

0.5001273053662038


In [24]:
#creating numpy ndarrays
x=np.array([1,2,3,4,5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [25]:
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)
print(type(y))
print(y.shape) #returns rows and columns
print(y.size)  #returns size of the nd array
print(y.dtype) #returns type of data type stored in nd array



[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
(3, 3)
9
int64


In [26]:
z = np.array(['Hello','World'])
print(type(z))
print(z.dtype)

<class 'numpy.ndarray'>
<U5


In [27]:
a = np.array([1,2.5,6])
print(a,a.dtype) #upcasts the data types to make the array of same data type

[1.  2.5 6. ] float64
